# Generated by Django 3.0.7 on 2020-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djg03app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='book_read_counte',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='book_support_counte',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_com',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_sup',
            field=models.IntegerField(default=0),
        ),
    ]
