# Generated by Django 3.0.7 on 2020-06-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djg02app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hage',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
