# Generated by Django 3.0.7 on 2020-07-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djg04app', '0002_auto_20200711_2139'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chinainfo',
            managers=[
            ],
        ),
    ]
