# Generated by Django 3.0.7 on 2020-07-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='China_AreaInfo',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name字段地区名称')),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djg10app.China_AreaInfo')),
            ],
            options={
                'db_table': 'china_areainfo',
            },
        ),
    ]
