# Generated by Django 3.0.7 on 2020-07-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djg10app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='china_areainfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
